"""Copy the repo-root README into packages/graxella/README.md.

setuptools refuses a `readme` path outside the package directory (a
sandboxing rule for sdist builds), so PyPI's description can't just point
at the root README directly -- it has to be a same-directory copy. This
script is the one place that copy is produced; scripts/check_readme_sync.py
verifies in CI that nobody edited the copy out from under it.

Run after any edit to the root README.md:  uv run python scripts/sync_readme.py
"""
from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "README.md"
DST = REPO / "packages" / "graxella" / "README.md"

MARKER = (
    "<!-- AUTO-COPIED from the repo-root README.md by "
    "scripts/sync_readme.py -- do not edit this file directly, edit the "
    "root one and re-run that script. scripts/check_readme_sync.py "
    "enforces this in CI. -->\n\n"
)


def main() -> int:
    DST.write_text(MARKER + SRC.read_text(encoding="utf-8"), encoding="utf-8")
    print(f"synced {SRC.relative_to(REPO)} -> {DST.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
